[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# [programs.devnet] # use for deployment
# counter = "HfB2cjfBFP8LBdnHLPMvV7bLswPS8TuyFY8ugDVCWLxK" # use for deployment

[programs.localnet]
counter = "HfB2cjfBFP8LBdnHLPMvV7bLswPS8TuyFY8ugDVCWLxK"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet" # use for deployment
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


